### PR TITLE
feat: update property url syntax for dynamicFormik inputs

### PR DESCRIPTION
**Pull request by Okisa**
## Context

Jira Issue:
https://github.com/boomerang-io/roadmap/issues/238

Build Number:
~1.3.1-beta.4~ 1.4.0-beta.7

## Checklist:

- [x] Has been verified in an integrated environment
- [x] Has relevant unit and integration tests passing
- [x] Has no linting, test console, or browser console errors (best effort)
- [x] Has JSDoc comment blocks for complex code

### CODE REVIEW

**Comment by tlawrie** [comment]
Adding @timrbula to fan out the reviews.

**Comment by BenjaminRuby** [comment]
@Okisa this still appears to not be working for me. I tried your `3.4.10` tag in flow and then created an input parameter for a workflow as type URL. I tried to supply a defaultValue like the example of `$(tasks.Get Team ID.results.evaluation)` that Tyson gave and the url was invalid within formik

**Comment by Okisa** [comment]
> @Okisa this still appears to not be working for me. I tried your `3.4.10` tag in flow and then created an input parameter for a workflow as type URL. I tried to supply a defaultValue like the example of `$(tasks.Get Team ID.results.evaluation)` that Tyson gave and the url was invalid within formik

Hi @BenjaminRuby 
Can you describe how did you test? I was looking at the Execute HTTP Call task that Tyson mentioned and seems to work.
flow_url

**Comment by Okisa** [comment]
> @Okisa this still appears to not be working for me. I tried your `3.4.10` tag in flow and then created an input parameter for a workflow as type URL. I tried to supply a defaultValue like the example of `$(tasks.Get Team ID.results.evaluation)` that Tyson gave and the url was invalid within formik

Oh I see, this update was made on DynamicFormik, I think this form is not using it. I'll update there to handle this case.

**Review by BenjaminRuby — APPROVED** [review]

**Pull request merged**
