### PR TITLE
Feature iseec 886 welcome and user profile

### PR DESCRIPTION
**Pull request by timrbula**
## Context

- https://tools.boomerangplatform.net/jira/console/browse/ISEEC-886
- https://tools.boomerangplatform.net/jira/console/browse/ISEEC-719

## Checklist:

- [x] Has been verified in an integrated environment
- [x] Has relevant unit and integration tests passing
- [x] Has no linting, test console, or browser console errors (best effort)
- [x] Has JSDoc comment blocks for complex code

## PR Review Guidance

- Test in DEV environment with Launchpad/Admin/Catalog that have the latest beta tag of the component library
- Test UIShell integrations in that story vs the specific header item story. I was having issues w/ the data fetching consistently there
- User Profile deviates from the designs slightly but this was intentional for simplicity and to match the rest of the header driven modals
- I ended up not using Formik for this so its a bit of a hacky implementation but its only supposed to be around for one release so next time around we can make it better

## Additional Info

- Fixed a bunch of tests and some linting issues
- Fixed modal mounting and unmounting animation
- Fixed issue w/ the Leave Platform confirm modal (check in Live to see it messed up now)
- Updated dependencies to have single version of webpack for testing
- Updated testing dependencies for support for latest jsdom functionality, latest RTL features

### CODE REVIEW

**Review by LucasGrimauth — CHANGES_REQUESTED** [review]
Nice work on this Tim! Some things and nitpicks I noticed testing version `1.1.0-beta.2` on dev:
- Header menu
image

 1. The Header menu items need more width.
 2. The user's name row needs more height, a thin gray border below and a little more spacing from the left side.
 3. Needs more spacing between avatar and user name of 1 rem instead of 0.5rem.
 4. The menu items text need a stronger font-weight of 600 instead of 500 and color #F2F4F8 instead of #c0c7ce.

- Profile Settings Modal
 1. The modal header title doesn't show the user name, it shows just "User profile"
 2. The team names do not gray out when not selected.
image

 3. Each team row need less height.
 4. The "Team Name" header needs a stronger font-weight than the team names in each row.
 5. Needs more spacing between team names and checkboxes.
 6. The "Save Changes" button is not disabled when there is no change or when is submitting changes.
 7. Need to refetch/invalidate queries so the data is updated after saving changes when the user is in Launchpad.

**Comment by timrbula** [comment]
hey @LucasGrimauth thanks for the detailed review. I cut corners on this b/c this is a short lived feature for demonstration purposes (They want to be able to demo to multiple clients and not worry about one client seeing another clients team for example). We are planning to have a more detailed user profile next release. 

That being said, good finds on some of these design discrepancies and I will try to fix them when I have time today.

**Review by Okisa — COMMENTED** [review]
Hi Tim!
I think Lucas covered most of the relevant points. One thing I noticed that could be considered is the fact that most of the Header modals ( ReportBug, ContactUs and now the UserProfile ) contain forms, so shouldn't they be only able to close by explicit clicking at the close or cancel buttons to avoid any lost of content?

**Comment by timrbula** [comment]
@Okisa Thanks yeah that is a great point. I have pushed on last update for this release to do that the modals that have forms

**Comment by timrbula** [comment]
@LucasGrimauth Fixed most of what you had except

2. Something looked off w/ the input where it was always enabled so wasn't able to key on that status
7. The header isn't hooked into react-query, I didn't want to include it in the component lib since other teams use this beyond use and I didn't want to have to make any breaking changes for any consumers of the header for it to work. So for people on Launchpad they will have to refresh unfortunately. I could have added in an additional prop to the UIShell that makes it was down to the ProfileSettings component to refetch but I didn't want to do that

**Pull request merged**
