### PR TITLE
feat: [ISEEC-1680] UI - Empty States Error Pages

### PR DESCRIPTION
**Pull request by duotive**
## Context

Jira Issue:

https://tools.boomerangplatform.net/jira/console/browse/ISEEC-1680

Build Number:

## Checklist:

- [x] Has been verified in an integrated environment
- [x] Has relevant unit and integration tests passing
- [x] Has no linting, test console, or browser console errors (best effort)
- [x] Has JSDoc comment blocks for complex code

### CODE REVIEW

**Comment by duotive** [comment]
@BenjaminRuby i have updated the code according to the discussions and the talk i had with Andrei

**Review by LucasGrimauth — DISMISSED** [review]
Looks good to me!

**Comment by BenjaminRuby** [comment]
Hey @duotive could you please convert the SVG files you added into javascript (you can use an online tool to convert svgs into react components)?

you should confirm that the graphics appear as expected and that you can run `npm run build` - our packaging build has had trouble with SVGs in the past

**Comment by duotive** [comment]
Hey @BenjaminRuby, i have changed them to SVG components.

**Review by BenjaminRuby — APPROVED** [review]

**Pull request merged**
