### PR TITLE
feat: fix and update autosuggest

### PR DESCRIPTION
**Pull request by timrbula**
# PR

The AutoSuggest component doesn't work

## Context

Version Number: 4.0.2-beta.0

## Checklist

- [x] Has been verified in an integrated environment
- [x] Has relevant unit and integration tests passing
- [x] Has no linting, test console, or browser console errors (best effort)
- [x] Has JSDoc comment blocks for complex code

## PR Review Guidance

I tested locally in Storybook and with Flow in https://github.com/boomerang-io/flow.client.web/pull/174

## Additional Info

Just need to make sure that you can make multiple selections and the cursor stays in the correct position, you can cycle through options, etc

### CODE REVIEW

**Review by BenjaminRuby — APPROVED** [review]
Hey @timrbula - nice changes here, it was looking good to me and confirmed in flow

**Review by LucasGrimauth — APPROVED** [review]
Tested on flow and looked good!

**Review by Okisa — CHANGES_REQUESTED** [review]
Nice changes Tim! 
I was testing things and noticed that the input works at first, but if you delete the content and try to type another thing the suggestion doesn't show up. Is this behavior expected?

autosuggest

**Comment by timrbula** [comment]
> Nice changes Tim! I was testing things and noticed that the input works at first, but if you delete the content and try to type another thing the suggestion doesn't show up. Is this behavior expected?
> 

hey @isakawa-carbon I need to publish a new beta version w/ the latest changes I made and update Flow. I'll do that now.

**Pull request merged**
