### PR TITLE
Feat iseec 4458 app switcher carbon v11 header

### PR DESCRIPTION
**Pull request by Okisa**
## Context

Jira Issue:
ISEEC-4458

Build Number:
3.0.0-beta.22

## Checklist:

- [ ] Has been verified in an integrated environment
- [ ] Has relevant unit and integration tests passing
- [ ] Has no linting, test console, or browser console errors (best effort)
- [ ] Has JSDoc comment blocks for complex code

### CODE REVIEW

**Review by BenjaminRuby — CHANGES_REQUESTED** [review]
Hey @Okisa could you add a hover state for `HeaderAccordionItem`? Now it just appears to the user that the entire accordion expanded area is active

**Comment by timrbula** [comment]
image
How does this look for the empty state? I think it makes sense to have the text match

**Comment by BenjaminRuby** [comment]
> image
> 
> How does this look for the empty state? I think it makes sense to have the text match

@timrbula we do have a design for the empty state: https://www.figma.com/proto/tW70MuoEnvkRMkD0jwDiwB/Core?node-id=5670%3A594666&scaling=min-zoom&page-id=576%3A266176

**Comment by Okisa** [comment]
I added a style for the text when hovering, how does it look? Or should we remove the general active hover style and add just when we hover an specific service?

app_switcher_test

**Comment by timrbula** [comment]
> > image
> > How does this look for the empty state? I think it makes sense to have the text match
> 
> @timrbula we do have a design for the empty state: https://www.figma.com/proto/tW70MuoEnvkRMkD0jwDiwB/Core?node-id=5670%3A594666&scaling=min-zoom&page-id=576%3A266176

Thanks, I looked but didn't see it.

**Comment by timrbula** [comment]
image
this shows most of the states

**Review by BenjaminRuby — DISMISSED** [review]
@Okisa @timrbula reviewed the code as well as the beta version in dev - it is looking really good to me!

**Pull request merged**
