### PR TITLE
Fix [ISEEC-2399] UIShell Accessibility

### PR DESCRIPTION
**Pull request by LucasGrimauth**
## Context

Jira Issue: ISEEC-2399

Build Number: 1.2.4-beta.1

## Checklist:

- [ ] Has been verified in an integrated environment
- [ ] Has relevant unit and integration tests passing
- [ ] Has no linting, test console, or browser console errors (best effort)
- [ ] Has JSDoc comment blocks for complex code

## PR Review Guidance

Test if UIShell is accessible by tab and enter.

### CODE REVIEW

**Comment by MthdeSouza** [comment]
ISEEC-2399 task is duplicated, this issue is handle on ISEEC-2378 task.

**Comment by timrbula** [comment]
@LucasGrimauth as @MthdeSouza has said this is a duplicate task, can this be closed?

**Comment by LucasGrimauth** [comment]
> @LucasGrimauth as @MthdeSouza has said this is a duplicate task, can this be closed?

Yeah, ISEEC-2399 is duplicated from ISEEC-2378.

**Comment by timrbula** [comment]
Closing in favor of #49 ISEEC-2378

**Pull request closed without merging**
